### ISSUE TITLE
Browser cache problem

### ISSUE THREAD

**Issue by WinterCool2968** [efwGrp/efw3.X#1]
After an error occurred, the only way i can operate this project correctly is to clean the browser cache everytime.Is this a problem?
error : 
実行時エラーが発生しました。
eventId=login_last
message=InternalError: Java class "[B" has no public instance field or method named "toJSON". (#173)

I found where the error occurred! it's in the login_last.js
So i made the '.runat()' into a comment, then the error disappeared.
return (new Result())
//.runat()
.withdata({"#txt_uid":cookie.get("txt_uid"),"#txt_pwd":""});

**Comment by changkejun** [comment]
Thank you for your connecting.
It is a bug about server.cookie.js in efw.3.####.jar. I forgot test it in javajdk1.7 .
Please change your jar to efw-3.5.016.jar. It will be right.

**Comment by WinterCool2968** [comment]
excuse me,i found the same problem like i asked several days ago.
when i excute a method in java and want to get the return value,then the problem occured again.
is this a bug?

実行時エラーが発生しました。
eventId=sample_save
message=InternalError: Java class "[B" has no public instance field or method named "toJSON". (#173)

here are the details:

js File:
var sample_save={};
sample_save.name="保存文件";
sample_save.paramsFormat={
	"#nom":"required:true;display-name:用户名",
};
sample_save.fire=function(params){
	var nom=params["#nom"];
	var rsPwd= (db.select("download_detailInfo","download",{"nom":nom}))
	.map({"INFO":"BOOKID"}).getArray();
	 var XXX = Packages.create.PoiCommon.CreateHtml(nom, "D:\Tomcat 7.0\webapps\efw-3.0-oracl\WEB-INF\efw\storage");
	 return (new Result()).alert(XXX);  //  error
         return (new Result()).alert(123);  // correct

};
----------------------------------------------------------------------------------------------------
java File:

package create;
public class PoiCommon {
    public static String CreateHtml(String pname,String purl){
	System.out.println(pname);
	System.out.println(purl);
	return purl;
    }
}
