### ISSUE TITLE
double型データのフォーマット結果がおかしい

### ISSUE THREAD

**Issue by zouhp841004** [efwGrp/efw3.X#19]
-----取得データ-----
aaa=-6.245004513516506e-17

-----aaa.format("0.000")-----
bbb=new Number(aaa.format("0.000"))
結果
0
----------.format("0.0%")-----
ccc=bbb.format("0.0%").replace(/%/,"")
結果
"-0.0"

**Comment by changkejun** [comment]
さすが、これはしょうがないと思う。保留。
