### ISSUE TITLE
wiki改善

### ISSUE THREAD

**Issue by duyuxuan** [efwGrp/efw3.X#3]
api可以利用这个项目来建设，我感觉不错。可以设置多语种。
https://github.com/GitbookIO/gitbook
参考案例：http://webmagic.io/docs/

**Comment by changkejun** [comment]
我才把.help 搞差不多...  你有体力吗?  做个menu看看如何?

**Comment by duyuxuan** [comment]
好的，我先做个menu，顺带熟悉熟悉API。前几天我把efw.jp的域名给购买了。.org的没有了。我顺带就先用它部署试试。以后能用到的话，这个域名也可以无偿捐赠。wiki初期做好了，我邮件联系您。

**Comment by changkejun** [comment]
好!
