### ISSUE TITLE
关于efw框架的相关问题

### ISSUE THREAD

**Issue by WinterCool2968** [efwGrp/efw3.X#4]
efw框架中我们需要使用
efw("xxxx.js")来跳转到相应的js后台
但是如果我想通过别的途径来跳转到js的后台是否可行？（即像跳转某个action一样跳转到efw框架中的某个js）

**Comment by changkejun** [comment]
没有看懂. 你是说 form post的那个 action 吗? 举个例子说说吧.

**Comment by WinterCool2968** [comment]
不好意思没说清楚，但是问题已经解决了，实在是不好意思，打扰了
